name: Release NuGet Package

on:
    # merge to master from pull request
    pull_request:
      types:
        - closed
      branches:
        - master
        - main
      paths-ignore:
        - '**.md'

env:
  DOTNET_NOLOGO: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

jobs:
  build-and-pack:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: | 
            6.x
            7.x
          source-url: https://nuget.pkg.github.com/${{ github.repository }}/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Gen Changelog and Tag sources
        id: changelog
        uses: TriPSs/conventional-changelog-action@latest
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Restore dependencies
        run: dotnet restore **/*.csproj

      - name: Build
        run: dotnet build **/*.csproj --configuration Release /p:ContinuousIntegrationBuild=true /p:Version=${{ steps.changelog.outputs.tag }} --no-restore

      - name: Pack
        run: dotnet pack src/**/*.csproj --configuration Release /p:Version=${{ steps.changelog.outputs.tag }} --no-build --output .
      
      - name: Push NuGet to GitHub packages
        run: dotnet nuget push *.nupkg --source https://nuget.pkg.github.com/$GITHUB_REPOSITORY_OWNER/index.json --skip-duplicate --no-symbols true

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            tag_name: ${{ steps.changelog.outputs.tag }}
            name: ${{ steps.changelog.outputs.tag }}
            body: ${{steps.changelog.outputs.clean_changelog}}
            draft: false
            prerelease: false
            files: |
              *.nupkg
 
      - name: Final Message
        run: echo "🎉 Success!"
